### ISSUE TITLE
literal strings in titles are too small

### ISSUE THREAD

**Issue by cocoatomo** [naoiwata/sphinxjp.themes.tinkerbelizeholesidebar#1]
see http://tink.elliptium.net/2015/09/20/applicative_functors_are_strong_lax_monoical_functors.html#applicative-monoidal

**Comment by naoiwata** [comment]
thx! I'll fix this as soon as possible.

**Comment by naoiwata** [comment]
Fixed on version 0.2.2.
thank u!
